# Generated by Django 4.1.4 on 2022-12-21 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friendship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='from_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='from_one_user', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='to_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_another_user', to=settings.AUTH_USER_MODEL, verbose_name='Receiver'),
        ),
    ]
