# Generated by Django 4.1.4 on 2022-12-21 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='users/posts/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=1500)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_posts', to=settings.AUTH_USER_MODEL)),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_profile.property')),
                ('where_published', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_published', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
